### ISSUE TITLE
RDB desyncs permissions on tickets when creating user rejoins server

### ISSUE THREAD

**Issue by iamlanjt** [Roblox-Developers/RDB-Proposals#2]
**What you saw**
When creating a ticket (on an alt), rejoining, and trying to find that ticket, it was a locked channel.

**What you expected**
RDB should have a case in the member join event which syncs permissions again (or, if the ticket is empty, it should be deleted automatically or some sort of visual feedback should be given to let staff know that the user cannot see the ticket).

**To Reproduce**
1. Be on an account with no permissions
2. Open a ticket
3. Leave RD
4. Join RD
5. View tickets category and see that it is now empty

**Screenshots**
N/A

**When**
08/10/2024 (MM/DD/YYYY) 3:30PM EST

**Additional context**
N/A

**Comment by Thunderlord677** [comment]
Should be fixed now.
